import { Router, type IRouter } from "express";
import healthRouter from "./health";
import teamsRouter from "./teams";
import playersRouter from "./players";
import kitsRouter from "./kits";
import fundraisingRouter from "./fundraising";
import pledgesRouter from "./pledges";
import logisticsRouter from "./logistics";
import dashboardRouter from "./dashboard";
import contributionsRouter from "./contributions";
import adminAuthRouter from "./adminAuth";
import sponsorsRouter from "./sponsors";
import matchesRouter from "./matches";
import publicSquadRouter from "./publicSquad";
import playerAuthRouter from "./playerAuth";
import eventsRouter from "./events";
import announcementsRouter from "./announcements";
import emailTemplatesRouter from "./email-templates";
import whatsappTemplatesRouter from "./whatsapp-templates";
import documentsRouter from "./documents";
import { auctionAdminRouter, auctionPublicRouter } from "./auction";
import pushRouter from "./push";
import newsRouter from "./news";
import { legoJarPublicRouter, legoJarAdminRouter } from "./lego-jar";
import funRunRouter from "./fun-run";
import pollsRouter from "./polls";
import payoutsRouter from "./payouts";
import siteContentRouter from "./site-content";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/teams", teamsRouter);
router.use("/players", playersRouter);
router.use("/kits", kitsRouter);
router.use("/fundraising", fundraisingRouter);
router.use("/pledges", pledgesRouter);
router.use("/logistics", logisticsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/contributions", contributionsRouter);
router.use("/admin/auth", adminAuthRouter);
router.use("/sponsors", sponsorsRouter);
router.use("/matches", matchesRouter);
router.use("/public", publicSquadRouter);
router.use("/player-auth", playerAuthRouter);
router.use("/events", eventsRouter);
router.use("/announcements", announcementsRouter);
router.use("/email-templates", emailTemplatesRouter);
router.use("/whatsapp-templates", whatsappTemplatesRouter);
router.use("/documents", documentsRouter);
router.use("/auction", auctionAdminRouter);
router.use("/public/auction", auctionPublicRouter);
router.use("/push", pushRouter);
router.use("/news", newsRouter);
router.use("/lego-jar", legoJarPublicRouter);
router.use("/admin/lego-jar", legoJarAdminRouter);
router.use("/fun-run", funRunRouter);
router.use("/polls", pollsRouter);
router.use("/payouts", payoutsRouter);
router.use("/site-content", siteContentRouter);

export default router;
