import { pgTable, serial, text, boolean, integer, numeric, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { teamsTable } from "./teams";

export const playersTable = pgTable("players", {
  id: serial("id").primaryKey(),
  teamId: integer("team_id").references(() => teamsTable.id).notNull(),
  accessToken: text("access_token").unique(),
  name: text("name").notNull(),
  shirtNumber: integer("shirt_number"),
  email: text("email").notNull(),
  phone: text("phone"),
  position: text("position"),
  dateOfBirth: text("date_of_birth"),
  nationality: text("nationality"),
  hkidNumber: text("hkid_number"),
  passportNumber: text("passport_number"),
  passportExpiry: text("passport_expiry"),
  passportCopyUrl: text("passport_copy_url"),
  emergencyContactName: text("emergency_contact_name"),
  emergencyContactPhone: text("emergency_contact_phone"),
  flightArrivalDateTime: text("flight_arrival_date_time"),
  flightDepartureDateTime: text("flight_departure_date_time"),
  arrivalCity: text("arrival_city"),
  outboundFlightNumber: text("outbound_flight_number"),
  outboundDepartureDateTime: text("outbound_departure_date_time"),
  returnFlightNumber: text("return_flight_number"),
  returnArrivalDateTime: text("return_arrival_date_time"),
  roomSharingPreference: text("room_sharing_preference"),
  roomSharingWith: text("room_sharing_with"),
  accommodationName: text("accommodation_name"),
  accommodationAddress: text("accommodation_address"),
  accommodationPhone: text("accommodation_phone"),
  accommodationEmail: text("accommodation_email"),
  insuranceProvider: text("insurance_provider"),
  insurancePolicyNumber: text("insurance_policy_number"),
  insuranceEmergencyPhone: text("insurance_emergency_phone"),
  insurancePolicyHolder: text("insurance_policy_holder"),
  insuranceExpiry: text("insurance_expiry"),
  insuranceEmail: text("insurance_email"),
  shirtSize: text("shirt_size"),
  shortsSize: text("shorts_size"),
  jacketSize: text("jacket_size"),
  poloSize: text("polo_size"),
  trackTopSize: text("track_top_size"),
  goalieSmockSize: text("goalie_smock_size"),
  travelDates: text("travel_dates"),
  feePaid: boolean("fee_paid").default(false).notNull(),
  paymentAmountDue: numeric("payment_amount_due", { precision: 10, scale: 2 }),
  paymentAmountPaid: numeric("payment_amount_paid", { precision: 10, scale: 2 }),
  paymentDate: text("payment_date"),
  dietaryRequirements: text("dietary_requirements"),
  medicalNotes: text("medical_notes"),
  notes: text("notes"),
  passportCopyReviewed: boolean("passport_copy_reviewed").default(false).notNull(),
  passportCopyUploadedAt: timestamp("passport_copy_uploaded_at"),
  passportCopyUploadedIsUpdate: boolean("passport_copy_uploaded_is_update").default(false).notNull(),
  instagramHandle: text("instagram_handle"),
  facebookHandle: text("facebook_handle"),
  travelNote: text("travel_note"),
  travelReminderSentAt: timestamp("travel_reminder_sent_at"),
  feeReminderSentAt: timestamp("fee_reminder_sent_at"),
  insuranceReminderSentAt: timestamp("insurance_reminder_sent_at"),
  onboardingInviteSentAt: timestamp("onboarding_invite_sent_at"),
  lastPortalAccessAt: timestamp("last_portal_access_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertPlayerSchema = createInsertSchema(playersTable).omit({ id: true, createdAt: true });
export type InsertPlayer = z.infer<typeof insertPlayerSchema>;
export type Player = typeof playersTable.$inferSelect;
